# Generated by Django 2.2.7 on 2019-12-02 11:01

import astrosat_users.models.models_profiles
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ExampleProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True, help_text="Age in years.", null=True
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, help_text="Height in centimeters.", null=True
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="Weight in kilograms.", null=True
                    ),
                ),
                (
                    "user",
                    astrosat_users.models.models_profiles.UserProfileField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
