# Generated by Django 2.2 on 2019-08-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20190822_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherExampleProfile',
        ),
    ]
