# Generated by Django 2.2 on 2019-08-22 22:35

import astrosat_users.profiles
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("example", "0004_delete_anotherexampleprofile")]

    operations = [
        migrations.AlterField(
            model_name="exampleprofile",
            name="user",
            field=astrosat_users.profiles.UserProfileField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="example_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
