# Generated by Django 2.2.5 on 2019-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0003_userpermission_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='astrosat_users.UserRole'),
        ),
    ]
