# Generated by Django 3.0.4 on 2020-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0004_auto_20191202_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(
                default=False,
                help_text='Has this user accepted the terms & conditions?'
            ),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='require_terms_acceptance',
            field=models.BooleanField(
                default=False,
                help_text=
                'Require a user to accept the terms & conditions during the sign up process.'
            ),
        ),
    ]
