# Generated by Django 3.0.6 on 2020-06-11 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0007_customer_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='_users',
            field=models.ManyToManyField(related_name='customers', through='astrosat_users.CustomerUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='customers', to='astrosat_users.UserRole'),
        ),
    ]
