# Generated by Django 3.0.7 on 2020-06-22 18:57

import astrosat_users.models.models_users
import astrosat_users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0008_auto_20200612_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=astrosat_users.models.models_users.user_avatar_path,
                validators=[
                    astrosat_users.validators.ImageDimensionsValidator()
                ]
            ),
        ),
    ]
