# Generated by Django 3.0.8 on 2020-07-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0010_auto_20200623_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='roles',
        ),
    ]
