# Generated by Django 3.0.8 on 2020-07-21 17:34
import uuid

from django.db import migrations


def update_user_uuids(apps, schema_editor):
    UserModel = apps.get_model("astrosat_users", "User")

    for user in UserModel.objects.all():
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0016_customeruser_invitation_date'),
    ]

    operations = [
        migrations.RunPython(
            update_user_uuids, reverse_code=migrations.RunPython.noop
        ),
    ]
