# Generated by Django 3.1 on 2020-10-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0020_user_requires_customer_registration_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MULTIPLE', 'Multiple')], max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='official_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
