# Generated by Django 3.1 on 2020-10-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0021_auto_20201015_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='requires_customer_registration_completion',
        ),
        migrations.AddField(
            model_name='user',
            name='registration_stage',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('USER', 'User'), ('CUSTOMER', 'Customer'), ('CUSTOMER_USER', 'CustomerUser'), ('ORDER', 'Order')], help_text='Indicates which stage of the registration process a user is at.', max_length=128, null=True),
        ),
    ]
