# Generated by Django 3.1 on 2020-10-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0023_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='Has this user been onboarded?'),
        ),
    ]
