# Generated by Django 3.1 on 2020-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0024_user_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_stage',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('USER', 'User'), ('CUSTOMER', 'Customer'), ('CUSTOMER_USER', 'CustomerUser'), ('ONBOARD', 'Onboard'), ('ORDER', 'Order')], help_text='Indicates which stage of the registration process a user is at.', max_length=128, null=True),
        ),
    ]
