# Generated by Django 3.2.7 on 2021-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0028_usermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
