# Generated by Django 3.2.12 on 2022-04-04 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0029_customer_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='verify_email_timeout',
            field=models.FloatField(default=3, help_text='Timeout (in days) of email verification tokens.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
