# Generated by Django 3.2.12 on 2022-04-06 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat_users', '0030_usersettings_verify_email_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='verify_email_timeout',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_token_timeout',
            field=models.FloatField(default=3, help_text='Timeout (in days) of email verification token.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='password_token_timeout',
            field=models.FloatField(default=259200, help_text='Timeout (in seconds) of password verification token.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
